bf16: true
cutoff_len: 2048
dataset: stage_2_justtest_6_26_train_without_cot
dataset_dir: data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_config.json
do_train: true
double_quantization: true
enable_thinking: true
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 32
lora_dropout: 0
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /media/guo/E/work/mywork_1/LLM_model/LLM-Research/Meta-Llama-3.1-8B
num_train_epochs: 50.0
optim: adamw_torch
output_dir: saves/Llama-3.1-8B/lora/train_2025-06-26-11-22-30-just-test-witcoutot
packing: false
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 4
quantization_method: bnb
report_to: none
save_steps: 50
stage: sft
template: default
trust_remote_code: true
warmup_steps: 5
